# SGC Configuration - Listener (Subscriber)
#
# This robot subscribes to /chatter from remote publishers.

group_secret = "test_cert"
signaling_server = "ws://3.18.194.127:8000"
routing_server = "3.18.194.127:8002"

[[topics]]
name = "/chatter"
type = "std_msgs/msg/String"
role = "subscriber"
