# SGC Configuration - Docker Talker
#
# Publisher config for docker-compose demo.

group_secret = "demo"
signaling_server = "ws://signal:8000"
routing_server = "rib:6379"

[[topics]]
name = "/chatter"
type = "std_msgs/msg/String"
role = "publisher"
