# SGC Configuration - Talker (Publisher)
#
# This robot publishes /chatter to remote subscribers.

group_secret = "test_cert"
signaling_server = "ws://3.18.194.127:8000"
routing_server = "3.18.194.127:8002"

[[topics]]
name = "/chatter"
type = "std_msgs/msg/String"
role = "publisher"
