[package]
name = "sgc"
version = "0.1.0"
authors = ["Eric Chen <kych@berkeley.edu>", "Jiachen Yuan <jcyuan_johnson@berkeley.edu>"]
edition = "2021"
repository = "https://github.com/BerkeleyAutomation/fogros2-sgc"
readme = "README.md"
license = "Apache-2.0"
keywords = ["ros2", "robotics", "networking", "webrtc"]
description = "FogROS2-SGC: Secure Global Connectivity for ROS2"

[workspace]
members = [
    "utils",
    "cli",
    "core",
    "signaling",
]

[features]
nightly = ["utils/nightly"]

[dependencies]
utils = { path = "utils" }
cli = { path = "cli" }
core = { path = "core" }
human-panic = "1.0.3"
better-panic = "0.3.0"
log = { version = "0.4.14", features = ["release_max_level_off"] }
env_logger = "0.10.0"

[dev-dependencies]
assert_cmd = "2.0.4"
predicates = "2.1.1"

[profile.dev]
opt-level = 0
debug = true
lto = false

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
